### ISSUE TITLE
ラーメンのレビューを翼さんと共有してください

### ISSUE THREAD

**Issue by s1f102101637-oki** [s1f102101637-oki/team-project#16]
翼さんはレビューをもらって店舗情報を作る際に参考にしてください

**Comment by s1f102101132** [comment]
店舗名：たち花
　店内は座席数が約７席とこじんまりとした雰囲気、夫婦二人で切り盛りをしているようだ。
注文：ざるラーメン（冷製つけ麺）
値段：700円（税込）
　つけ麺なのかラーメンなのか悩んだ末注文。多分ラーメン。夏季限定で9月末まで。
　ちなみに店内BGMはクラシック。
　スープは醤油ベースでさっぱりしているがゴマとネギが乗っているので食べてる感ある。
　麺は中細麺で、量も個人的には丁度よかった。具材は写真の通り、普通。
　生姜とワサビも付いてくるので途中から蕎麦食ってる感覚になったが、それくらい味変にはぴったりってことで。
　ランチタイム(11:30-14:00)だとご飯(白米かゆかりご飯)orデザートがサービスで付いてくる。無難においしい。
　冷やしメニューには冷えラーメンの他に冷やし担々麺、うま塩冷やし（混ぜそば）がある。
　看板メニューは「たち花」というラーメン。
　比較的安価でのんびり食事ができるため、アットホームな雰囲気が好きな人にはおすすめできると感じた。

まとめましたが、必要な情報だけ使ってください:)

**Comment by s1f101900330** [comment]
ありがとう！書いてみます！
