### ISSUE TITLE
fontサイズの変更

### ISSUE THREAD

**Issue by s1f102101637-oki** [s1f102101637-oki/team-project#6]
cssにbodyタグのなかで20pxにするコードを付け加えといてください

**Comment by s1f101900330** [comment]
やっておきます！

**Comment by s1f102101637-oki** [comment]
おそらく今日の23:59までにやらないと翼さんの今週までの課題としての評価がなくなってしまうので気を付けてください。

**Comment by s1f101900330** [comment]
あれ、できてない？

2021年6月24日(木) 13:20 s1f102101637-oki ***@***.***>:

**Comment by s1f102101637-oki** [comment]
八木澤さんとも確認してみたのですが反映されていないのでプッシュしたか確認してみてください。
プッシュしたのにって場合はレポジトリーからVScode開いてもう一度やってみてください。

**Comment by s1f102101637-oki** [comment]
変更の確認できました！
ありがとうございます

**Comment by s1f102101637-oki** [comment]
変更の確認できました！
ありがとうございました。
このコメントを見たらイシューをクローズしておいてください。
