### ISSUE TITLE
ラーメン店の共有

### ISSUE THREAD

**Issue by s1f102101637-oki** [s1f102101637-oki/team-project#9]
いったお店の名前と写真の確保報告をこのイシューのコメントで共有してください

**Comment by s1f101900330** [comment]
吟風　赤羽東口の家系ラーメン行ってきました
写真も確保できてます！

**Comment by s1f102101637-oki** [comment]
ありがとうございます！

**Comment by s1f102101637-oki** [comment]
必要ないとは思いますが今日糖朝でサンラータン麺食べて写真も撮っておきました。サイトが物足りない時の予備と思っておいてください。

**Comment by s1f102101132** [comment]
駅近くの「たち花」に行って写真も撮っておきました。おいしかったです。

**Comment by s1f102101637-oki** [comment]
通達遅くなりましたが「粋」に行ってきました。写真はアップロード済みです。
感想メモってくるの忘れてしまいました。ごめんなさい。
一応覚えている限りで…
油の量を選べる
味の濃さを選べる
麺の硬さを選べる
ライス無料
必要なら紙エプロンをもらえます
看板商品は豚骨しょう油らーめん、500円、替え玉100円
味は家系豚骨ラーメンでクセがあまり強くないのでどんな人でもおいしく食べられそうな印象でした。スープはごはんと一緒にいただくと止まらなくなる。
